%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook:
%    C:\D-ADoMC\LDA\Colors_and_Words\Color_Semantics_Test_II_Results\Color_Semantics_Test_II_03-08-2014.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/03/08 21:47:23

%% Import the data
[~, ~, ColorSemanticsTestII03082014] = xlsread('./Color_Semantics_Test_III_04-12-2015.xlsx','J1:ND445');
ColorSemanticsTestII03082014(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),ColorSemanticsTestII03082014)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),ColorSemanticsTestII03082014); % Find non-numeric cells
%ColorSemanticsTestII03082014(R) = {NaN}; % Replace non-numeric cells

%% Clear temporary variables
clearvars R;
data = ColorSemanticsTestII03082014;
clear ColorSemanticsTestII03082014;